language: python 
python: 
  - "3.6"
env: 
  - DJANGO=2.0 DB=postgres
services:
  - postgresql
addons:
  postgresql: "9.6"


before_install: 
  - cd decide
install: 
  - pip install -r ../requirements.txt
before_script:
  - psql -c "create user decide with password 'decide'" 
  - psql -c "create database decide owner decide"
  - python manage.py migrate
script:
  - cp local_settings.travis.py local_settings.py
  - python manage.py test

if: branch=master
